### PR TITLE
Added python tests in unit testing.

### PR DESCRIPTION
**Pull request by psigen**
This PR adds `add_test()` directives that run python unit tests against the generated code.  These were previously available, but not run directly through CTest.

I also modified the code in `01_function` to exacerbate the bug in #168, so we will need to fix that bug before unit tests will pass again.

### CODE REVIEW

**Comment by psigen** [comment]
Ok, this may have fixed #168, I am not sure.  The unit tests are now passing.

**Comment by jslee02** [comment]
I tested this with `dartpy`'s `dart-6.5` branch. It seems this change generates a function with not fully qualified argument types. For example, there is a generated binding, which wasn't generated before this change, that includes not fully qualified type:
```cpp
void _ZN4dart6commonL26getVectorObjectIfAvailableIPNS_8dynamics4NodeEEET_mRKSt6vectorIS5_SaIS5_EE()
{
::boost::python::object parent_object(::boost::python::scope().attr("common"));
::boost::python::scope parent_scope(parent_object);

::boost::python::def("getVectorObjectIfAvailable", [](std::size_t index, const std::vector<Node *> & vec) -> dart::dynamics::Node * { return dart::common::getVectorObjectIfAvailable<dart::dynamics::Node *>(index, vec); }, ::boost::python::return_value_policy<::boost::python::return_by_smart_ptr<dart::dynamics::NodePtr> >(), (::boost::python::arg("index"), ::boost::python::arg("vec")));

}
```
Note that `const std::vector<Node *>` should be `const std::vector<dart::dynamics::Node *>`.

**Comment by psigen** [comment]
Hmm, do you think there is any way to make a unit test for this case?

**Comment by psigen** [comment]
> Do we need to add all the source files to EXTRA_SOURCES option to get bindings of non-member functions?

No, we do not.  The purpose of the `EXTRA_SOURCES` option is to allow us to include `cpp` files that _should_ be compiled into the binding, but should _not_ be used to generate the binding.  This can be useful if we have various helper function implementations or similar things.

**Comment by jslee02** [comment]
> Hmm, do you think there is any way to make a unit test for this case?

Let's handle this case in a separate PR. Let me create an issue for this.

**Pull request merged**
