### PR TITLE
Add note about key length to README

### LINKED ISSUE #118: Update README.md for long key case
[`yaml-cpp` doesn't allow more than 1024 characters for a single line key](https://github.com/jbeder/yaml-cpp/blob/master/src/simplekey.cpp#L111). For longer key, we should use [multi-line key](http://stackoverflow.com/a/36295084). It would be good to mention about this on the readme.

### PR DESCRIPTION
**Pull request by mkoval**
I moved the description from the Wiki to the `README`. This fixes #118.

### CODE REVIEW

**Comment by jslee02** [comment]
I believe updating `REAME.md` is not the cause of CI failure. :rage:  (see #140).

**Comment by mkoval** [comment]
I am ignoring the CI failure and merging this, since @psigen identified the underlying issue [that is completely unrelated to this pull request].

**Comment by jslee02** [comment]
Are we okay to remove the wiki then?

**Comment by mkoval** [comment]
Done!

**Pull request merged**
