### PR TITLE
Disable parallel build on CI to avoid build failures

### PR DESCRIPTION
**Pull request by jslee02**
It seems CI builds irregularly fail due to parallel build. I've been re-running every failed CI tests whenever they failed. Not sure if this is related to #212.

### CODE REVIEW

**Comment by psigen** [comment]
Usually when this happens it is because an intermediate target is missing in a CMakeLists.txt somewhere.  Can you link some of the failing builds here so we can note what the specific errors were?

**Comment by jslee02** [comment]
[Here](https://travis-ci.org/github/personalrobotics/chimera/jobs/671324187#L2275-L2313) is an example case of the build failure.

**Comment by jslee02** [comment]
bump :smile:

**Comment by psigen** [comment]
I can't seem to pull up the logfiles for this.. is it possible TravisCI garbage collected them? :sweat:

**Comment by jslee02** [comment]
> I can't seem to pull up the logfiles for this.. is it possible TravisCI garbage collected them?

I cannot pull up the log as well. I think is not available temporarily. [This](https://dev.azure.com/personalrobotics/chimera/_build/results?buildId=401&view=logs&j=94c336d7-3d7e-58cb-3d8c-f4ecb4635230&t=7dfa75b3-90b8-5f9d-5a1e-3e87e121c1b8) is an equivalent error from Azure Pipelines.

**Comment by psigen** [comment]
Noting this as possibly related from [this log](https://dev.azure.com/personalrobotics/93bf7b9a-b481-40df-85fd-d81022b0cc16/_apis/build/builds/401/logs/78):
```
2020-04-04T16:23:02.1929291Z CMake Error at /usr/share/cmake-3.13/Modules/CTestTargets.cmake:28 (configure_file):
2020-04-04T16:23:02.1930280Z   configure_file Problem configuring file
2020-04-04T16:23:02.1930763Z Call Stack (most recent call first):
2020-04-04T16:23:02.1931525Z   /usr/share/cmake-3.13/Modules/CTest.cmake:264 (include)
2020-04-04T16:23:02.1932100Z   test/examples/CMakeLists.txt:1 (include)
```

**Comment by jslee02** [comment]
I have to admit that I wasn't able to pinpoint what the root cause, but this resolves the build error.

**Comment by psigen** [comment]
Would it be possible to enable verbose flags and monitor for the output?  I think there might be a build error that is being logged but not printed in here.

I am also ok with just merging this if it unblocks other development.  I just don't know how to replicate locally to figure out the issue outside of the CI system.

**Comment by jslee02** [comment]
> I am also ok with just merging this if it unblocks other development. I just don't know how to replicate locally to figure out the issue outside of the CI system.

Yeah, I would like to just merge this and create an issue to track this instead. I think there are other issues to be resolved that might be higher priority.

**Pull request merged**
